from app.schemas.common import ApiResponse
from app.schemas.auth import (
    RegisterEmailRequest,
    RegisterPhoneRequest,
    LoginEmailRequest,
    LoginPhoneStartRequest,
    OtpVerifyRequest,
    RefreshRequest,
    ForgotPasswordStartRequest,
    ResetPasswordConfirmRequest,
    TokenPair,
    AuthUser,
)
from app.schemas.rbac import (
    RoleCreate,
    RoleOut,
    PermissionCreate,
    PermissionOut,
    AssignRoleRequest,
    AssignPermissionToRoleRequest,
)

from app.schemas.curriculum import (
    LanguageCreate,
    LanguageUpdate,
    LanguageOut,
    LevelCreate,
    LevelUpdate,
    LevelOut,
    UnitCreate,
    UnitUpdate,
    UnitOut,
    LessonCreate,
    LessonUpdate,
    LessonOut,
)

from app.schemas.lesson_engine import (
    LessonItemCreate,
    LessonItemUpdate,
    LessonItemOut,
    ChoiceCreate,
    ChoiceOut,
    AttemptStartResponse,
    AttemptSubmitRequest,
    AttemptSubmitResponse,
    AttemptOut,
    AttemptsListResponse,
    AttemptAIUpdateRequest,
    AttemptAIUpdateResponse,
)
from app.schemas.vocabulary import *
from app.schemas.grammar_engine import (
    GrammarTopicCreate,
    GrammarTopicUpdate,
    GrammarTopicOut,
    GrammarPatternCreate,
    GrammarPatternUpdate,
    GrammarPatternOut,
    GrammarExampleCreate,
    GrammarExampleUpdate,
    GrammarExampleOut,
    GrammarExerciseCreate,
    GrammarExerciseUpdate,
    GrammarExerciseOut,
    GrammarChoiceCreate,
    GrammarChoiceUpdate,
    GrammarChoiceOut,
    AttachGrammarToLessonRequest,
    LessonGrammarOut,
    GrammarSessionResponse,
    GrammarSubmitRequest,
    GrammarSubmitResponse,
)
from app.schemas.speaking_engine import *
__all__ = [
    # common
    "ApiResponse",
    # auth
    "RegisterEmailRequest",
    "RegisterPhoneRequest",
    "LoginEmailRequest",
    "LoginPhoneStartRequest",
    "OtpVerifyRequest",
    "RefreshRequest",
    "ForgotPasswordStartRequest",
    "ResetPasswordConfirmRequest",
    "TokenPair",
    "AuthUser",
    # rbac
    "RoleCreate",
    "RoleOut",
    "PermissionCreate",
    "PermissionOut",
    "AssignRoleRequest",
    "AssignPermissionToRoleRequest",
    "LanguageCreate",
    "LanguageUpdate",
    "LanguageOut",
    "LevelCreate",
    "LevelUpdate",
    "LevelOut",
    "UnitCreate",
    "UnitUpdate",
    "UnitOut",
    "LessonCreate",
    "LessonUpdate",
    "LessonOut",
    "LessonItemCreate",
    "LessonItemUpdate",
    "LessonItemOut",
    "ChoiceCreate",
    "ChoiceOut",
    "AttemptStartResponse",
    "AttemptSubmitRequest",
    "AttemptSubmitResponse",
    "AttemptOut",
    "AttemptsListResponse",
    "AttemptAIUpdateRequest",
    "AttemptAIUpdateResponse",
    "LexemeCreate",
    "LexemeUpdate",
    "LexemeOut",
    "SenseCreate",
    "SenseUpdate",
    "SenseOut",
    "ExampleCreate",
    "ExampleUpdate",
    "ExampleOut",
    "AttachLexemesToLessonRequest",
    "LessonLexemeOut",
    "ReviewTodayResponse",
    "ReviewResultRequest",
    "WeakWordOut",
    "GrammarTopicCreate",
    "GrammarTopicUpdate",
    "GrammarTopicOut",
    "GrammarPatternCreate",
    "GrammarPatternUpdate",
    "GrammarPatternOut",
    "GrammarExampleCreate",
    "GrammarExampleUpdate",
    "GrammarExampleOut",
    "GrammarExerciseCreate",
    "GrammarExerciseUpdate",
    "GrammarExerciseOut",
    "GrammarChoiceCreate",
    "GrammarChoiceUpdate",
    "GrammarChoiceOut",
    "AttachGrammarToLessonRequest",
    "LessonGrammarOut",
    "GrammarSessionResponse",
    "GrammarSubmitRequest",
    "GrammarSubmitResponse",
    "SpeakingTaskCreate",
    "SpeakingTaskUpdate",
    "SpeakingTaskOut",
    "StartSpeakingAttemptRequest",
    "StartSpeakingAttemptResponse",
    "SpeakingAttemptItemOut",
    "SubmitSpeakingAttemptRequest",
    "SpeakingAttemptOut",
    "SpeakingScoreOut",
    
    
]
